# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 15:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180424_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 24, 15, 12, 14, 468961, tzinfo=utc)),
        ),
    ]
